default_context:
  project_name: 'todoapp'
  project_slug: 'todo_app'
  domain_main: 'localhost'
  domain_staging: 'stage.todo'
  docker_swarm_stack_name_main: 'localhost'
  docker_swarm_stack_name_staging: 'stage-todo'
  secret_key: '11223344'
  first_superuser: 'admin@admin.com'
  first_superuser_password: '11223344'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.localhost", "https://stage.todo", "https://localhost", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@admin.com'
  postgres_password: 'postgres'
  pgadmin_default_user: 'postgres'
  pgadmin_default_user_password: '11223344'
  traefik_constraint_tag: 'localhost'
  traefik_constraint_tag_staging: 'stage.todo'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:11223344'
  sentry_dsn: ''
  docker_image_prefix: 'todo-app'
  docker_image_backend: 'todo-appbackend'
  docker_image_celeryworker: 'todo-appceleryworker'
  docker_image_frontend: 'todo-appfrontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
