"""empty message

Revision ID: 74104fd20ff7
Revises: 50e81d43f7aa
Create Date: 2021-07-14 21:11:53.171939

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils.types.choice

# revision identifiers, used by Alembic.
revision = '74104fd20ff7'
down_revision = '50e81d43f7aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('is_completed', sa.Boolean(), nullable=True))
    op.add_column('todo', sa.Column('due_date', sa.Date(), nullable=True))
    op.add_column('todo', sa.Column('priority', sqlalchemy_utils.types.choice.ChoiceType(choices=(('NONE', 'None'), ('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'))), server_default='NONE', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo', 'priority')
    op.drop_column('todo', 'due_date')
    op.drop_column('todo', 'is_completed')
    # ### end Alembic commands ###
