"""empty message

Revision ID: e81ec7e33afa
Revises: 728952a5eaf6
Create Date: 2021-07-15 17:05:12.241566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e81ec7e33afa'
down_revision = '728952a5eaf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
